CREATE TABLE PessoaJuridica (
  idPJ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  CNPJ VARCHAR(11) UNIQUE NOT NULL,
  CONSTRAINT FK_PessoaJuridica_Pessoa FOREIGN KEY (idPJ) REFERENCES Pessoa(idPessoa)
);
